// pixel-art sprite data and species definitions — pure data

export const SPRITES = {
  tetra: [
    "f..bbbb..",
    "ff.bbbbb.",
    "ffbbbbeb.",
    "ff.bbbbb.",
    "f..bbbb..",
  ],
  guppy: [
    "ff....bbb...",
    "fff..bbbbbb.",
    ".fffbbbbbeb.",
    ".fffbbbbbbbb",
    "fff..bbbbbb.",
    "ff....bbb...",
  ],
  angel: [
    "....d.....",
    "...ddd....",
    "f..bbbb...",
    "ff.bbbbeb.",
    "ffbbbbbbbb",
    "ff.bbbbbb.",
    "f..bbbb...",
    "...ddd....",
    "....d.....",
  ],
  puffer: [
    "f...bbbb..",
    "ff.bbbbbb.",
    "ffbbbbbeb.",
    "ffbbbbbbbb",
    "ffbbbbbbb.",
    "ff.bbbbbb.",
    "f...bbbb..",
  ],
  pufferBig: [
    "....d.d.d....",
    "..d.bbbbb.d..",
    "...bbbbbbb...",
    ".d.bbbbbeb.d.",
    "f.bbbbbbbbb..",
    "fdbbbbbbbbbd.",
    "f.bbbbbbbbb..",
    ".d.bbbbbbb.d.",
    "...bbbbbbb...",
    "..d.bbbbb.d..",
    "....d.d.d....",
  ],
  starfish: [
    "...b...",
    "..bbb..",
    "bbbdbbb",
    ".bbdbb.",
    "..bbb..",
    ".bb.bb.",
    "bb...bb",
  ],
  seahorse: [
    "....bb..",
    "...bbbb.",
    "...beb..",
    "....bb..",
    "f.bbbb..",
    "fbbbb...",
    "fbbb....",
    ".bbb....",
    "..bb..b.",
    "...bbb..",
  ],
  whale: [
    "f.....bbbbbbbbbb......",
    "ff..bbbbbbbbbbbbbb....",
    ".ffbbbbbbbbbbbbbbbbb..",
    ".fbbbbbbbbbbbbbbbbebb.",
    "ffbbbbbbbbbbbbbbbbbbbb",
    ".fbbbbbbbbbbbbbbbbbbb.",
    "..bbbbbbbbbbbbbbbbbb..",
    "...dddddddddddddd.....",
    "....d..d..d..d........",
  ],
  clown: [
    "f..bdbbd..",
    "ff.bdbbdb.",
    "ffbbdbbdeb",
    "ff.bdbbdb.",
    "f..bdbbd..",
  ],
  sword: [
    "f...bbbb.......",
    "ff.bbbbbbb.....",
    "ffbbbbbbbebdddd",
    "ff.bbbbbbb.....",
    "f...bbbb.......",
  ],
  beluga: [
    "f.......bbbbbbbbb.........",
    "ff....bbbbbbbbbbbbbb......",
    ".ff.bbbbbbbbbbbbbbbbbb....",
    ".ffbbbbbbbbbbbbbbbbbbbbb..",
    ".fbbbbbbbbbbbbbbbbbbbbeb..",
    "ffbbbbbbbbbbbbbbbbbbbbbbd.",
    ".fbbbbbbbbbbbbbbbbbbbbbb..",
    "..bbbbbbbbbbbbbbbbbbbb....",
    "...bbbbbbbbbbbbbbbb.......",
    ".....ddddddddd............",
  ],
  goldfish: [
    "ff...bbbb..",
    "fff.bbbbbb.",
    ".ffbbbbbbeb",
    "fffbbbbbbbb",
    ".ffbbbbbbb.",
    "fff.bbbbbb.",
    "ff...bbbb..",
  ],
  zebra: [
    "f..dddddd.",
    "ffbbbbbbeb",
    "f..dddddd.",
    "ffbbbbbbbb",
    "f..dddddd.",
  ],
  molly: [
    "f...bbb..",
    "ff.bbbbb.",
    "ffbbbbbeb",
    "ff.bbbbb.",
    "f...bbb..",
  ],
  betta: [
    ".ff..fff....",
    "fff.bbbbbb..",
    "ffffbbbbbeb.",
    "fffbbbbbbbb.",
    "ffffbbbbbb..",
    "fff.bbbbbb..",
    ".ff..fff....",
  ],
  discus: [
    "....ddd....",
    "..dbbbbbd..",
    ".dbbbbbbbd.",
    "fdbbbbbbeb.",
    "ffbbbbbbbbd",
    "fdbbbbbbbb.",
    ".dbbbbbbbd.",
    "..dbbbbbd..",
    "....ddd....",
  ],
  bluetang: [
    "f....bbbb...",
    "ff.bbbbbbbb.",
    "fffbbbbbbeb.",
    "fffbbbbbbbb.",
    "ff.bbbbbbb..",
    "f....bbbb...",
  ],
  arowana: [
    "f...bbbbbbbbb.....",
    "ffbbbbbbbbbbbbbb..",
    "ffbbbbbbbbbbbbbeb.",
    "ffbbbbbbbbbbbbbb..",
    "f...bbbbbbbbb.....",
  ],
  coelacanth: [
    "f....bbbbbbbb.....",
    "ff.bbbbbbbbbbbb...",
    "ffbbbbbbbbbbbbbb..",
    "ffbbbbdbbdbbbbeb..",
    "ffbbbbbbbbbbbbbbb.",
    "ffbbbbdbbdbbbbbb..",
    "ff.bbbbbbbbbbbb...",
    "f...f..bbbbbf.....",
  ],
  hatchet: [
    "....bb.b.",
    "f.bbbbbb.",
    "ffbbbbbeb",
    "f.bbbbbb.",
    "..bbbb...",
    "...bb....",
    "....b....",
  ],
  angler: [
    "....c.....",
    "....d.....",
    "..bbbbb...",
    ".bbbbbbeb.",
    "fbbbbbbbbb",
    ".bbwwwbb..",
    "..bbbbb...",
  ],
  gulper: [
    "f............bbb..",
    "ff....bbbbbbbbbbb.",
    "ffbbbbbbbbbbbbbbeb",
    "ff....bbbbbbwwwww.",
    "f............bbb..",
  ],
  oarfish: [
    ".d.d.d.d.d.d.d.d.d.d..",
    "f.bbbbbbbbbbbbbbbbbb..",
    "ffbbbbbbbbbbbbbbbbbeb.",
    "f.bbbbbbbbbbbbbbbbbb..",
  ],
  bluewhale: [
    "f...........bbbbbbbbbb........",
    "ff......bbbbbbbbbbbbbbbbbb....",
    ".ff..bbbbbbbbbbbbbbbbbbbbbbb..",
    ".ffbbbbbbbbbbbbbbbbbbbbbbbbeb.",
    "ffbbbbbbbbbbbbbbbbbbbbbbbbbbb.",
    ".fbbbbbbbbbbbbbbbbbbbbbbbbbbbd",
    "..bbbbbbbbbbbbbbbbbbbbbbbbbb..",
    "...bbbbbbbbbbbbbbbbbbbbbb.....",
    "....dddddddddddddddddd........",
    ".....d...d...d...d............",
  ],
  giantsquid: [
    "....bbbb......",
    "...bbbbbb.....",
    "..bbbbbbbb....",
    "..bbbbbbbb....",
    "..bebbbbeb....",
    "..bbbbbbbb....",
    "..f.f..f.f....",
    "..f.f..f.f....",
    ".f..f..f..f...",
    ".f..f..f..f...",
    "f...f..f...f..",
    "f...f..f...f..",
  ],
  mola: [
    ".....dd.......",
    "...dbbbd......",
    "..dbbbbbd.....",
    ".dbbbbbbbbd...",
    "fdbbbbbbbbeb..",
    "ffbbbbbbbbbbd.",
    "ffbbbbbbbbbbd.",
    "fdbbbbbbbbbb..",
    ".dbbbbbbbbd...",
    "..dbbbbbd.....",
    "...dbbbd......",
    ".....dd.......",
  ],
  cory: [
    "..dbbbb..",
    "f.bbbbeb.",
    "ffbbbbbbd",
    "..bbbbbb.",
    "..dd.dd..",
  ],
  catfish: [
    ".....bbbbbb......",
    "f..bbbbbbbbbb..d.",
    "ffbbbbbbbbbbeb.d.",
    "ffbbbbbbbbbbbbdd.",
    "ff.bbbbbbbbbbb.d.",
    "f...bbbbbbbb.....",
    "......dddd.......",
  ],
  lionfish: [
    ".d.d.d.d.....",
    "..d.d.d.d....",
    "f..bbbbbb....",
    "ff.bbbbbeb...",
    "ffbbbbbbbbdd.",
    "ff.bbbbbb....",
    "f..bbbbbb....",
    "..d.d.d.d....",
    ".d.d.d.d.....",
  ],
  moray: [
    "f.bbbb....bbbb......",
    "ffbbbbbbbbbbbbbbbb..",
    "f.bbbbbbbbbbbbbbbeb.",
    "......bbbb.....bbww.",
  ],
  octopus: [
    "...bbbbbb...",
    "..bbbbbbbb..",
    ".bbbbbbbbbb.",
    ".bbebbbbeb..",
    ".bbbbbbbbbb.",
    "..bbbbbbbb..",
    "..f.f..f.f..",
    ".f..f..f..f.",
    ".f..f..f..f.",
    "f...f...f..f",
  ],
  ray: [
    "........bbbb......",
    "......bbbbbbbb....",
    "f...bbbbbbbbbbbb..",
    "ffddbbbbbbbbbbbeb.",
    "f...bbbbbbbbbbbb..",
    "......bbbbbbbb....",
    "........bbbb......",
  ],
  turtle: [
    ".....dddddd.....",
    "...ddbdbdbdd....",
    "..dbdbdbdbdbd...",
    ".ddbdbdbdbdbdbbb",
    ".dbdbdbdbdbdbbeb",
    "..ddddddddddbbb.",
    "..ff......ff....",
    ".ff......ff.....",
  ],
  dolphin: [
    "..........dd..........",
    "f......bbbbbbbb.......",
    "ff...bbbbbbbbbbbb.....",
    ".ffbbbbbbbbbbbbbbeb...",
    ".fbbbbbbbbbbbbbbbbbbww",
    "ffbbbbbbbbbbbbbbbbbb..",
    ".f..bbbbbbbbbbbbb.....",
    ".....bbbbbb...ff......",
  ],
  orca: [
    "...........bb.............",
    "..........bbbb............",
    "f.....bbbbbbbbbbbbb.......",
    "ff..bbbbbbbbbbbbbbbbbb....",
    ".ffbbbbbbbbbbbbbbbbddbb...",
    ".fbbbbbbbbbbbbbbbbbdedbww.",
    "ffbbbbbbddddbbbbbbbbddbbb.",
    ".fbbbbbbbdddddbbbbbbbbb...",
    "..bbbbbbbbbbbbbbbbbb......",
    "....bbbb....ff............",
  ],
  narwhal: [
    "f......bbbbbbbbbb.........",
    "ff...bbbbbbbbbbbbbb.......",
    ".ffbbbbbbbbbbbbbbbbeb.....",
    ".fbbbbbbbbbbbbbbbbbbbwwwww",
    "ffbbbbbbbbbbbbbbbbbbb.....",
    ".f..bbbbbbbbbbbbbb........",
    "......bbbbbbbb............",
  ],
  cherrysalmon: [
    "f...bbbbb....",
    "ff.bbdbdbbb..",
    "ffbbbbbbbbeb.",
    "ff.bbdbdbbb..",
    "f...bbbbb....",
  ],
  seabream: [
    "....dbbb....",
    "f..bbbbbb...",
    "ff.bbbbbbeb.",
    "ffbbbbbbbbbd",
    "ff.bbbbbbbb.",
    "f..bbbbbb...",
    "....bbb.....",
  ],
  butterflyfish: [
    "....dd....",
    "f..bbdb...",
    "ff.bbdbb..",
    "ffbbbdbeb.",
    "ffbbbdbbww",
    "ffbbbdbbb.",
    "ff.bbdbb..",
    "f..bbdb...",
    "....dd....",
  ],
  mackerel: [
    "f...dbdbdbd...",
    "ff.bbbbbbbbbb.",
    "ffbbbbbbbbbbeb",
    "ff.bbbbbbbbbb.",
    "f....bbbbb....",
  ],
  flyingfish: [
    "..ff.ff......",
    "..fff.ff.....",
    "f..fffbbb....",
    "ffbbbbbbbbeb.",
    "f..bbbbbbbb..",
    "....ffff.....",
    "......ff.....",
  ],
  manta: [
    "........bbbbbb..........",
    "....bbbbbbbbbbbb........",
    ".bbbbbbbbbbbbbbbbbb.....",
    "f.bbbbbbbbbbbbbbbbbbb.b.",
    "ffbbbbbbbbbbbbbbbbbeb.b.",
    "f..bbbbbbbbbbbbbbbb.....",
    ".....bbbbbbbbbb.........",
    ".........bbbb...........",
  ],
  salmon: [
    "f....bbbbbb.....",
    "ff.bbbbbbbbbb...",
    "ffbbbbbbbbbbbeb.",
    "ffbbbbbbbbbbbbww",
    "ff.bbbbbbbbbb...",
    "f....bbbbbb.....",
  ],
  gizzardshad: [
    "f..bbbbb...",
    "ff.bbbbbb..",
    "ffbbbbbbeb.",
    "ff.bbbbbbd.",
    "f..bbbbb...",
  ],
  cutlass: [
    "f.bbbbbbbbbbbbbbbbbb..",
    "fbbbbbbbbbbbbbbbbbbbeb",
    "f.bbbbbbbbbbbbbbbbbb..",
  ],
  cod: [
    ".....dbbbd.....",
    "f..bbbbbbbbbb..",
    "ffbbbbbbbbbbeb.",
    "ffbbbbbbbbbbbb.",
    "f..bbbbbbbbbb..",
    ".........d.....",
  ],
  icefish: [
    "f.bbbbbb..",
    "ffbbbbbbeb",
    "f.bbbbbb..",
  ],
  yellowtail: [
    "f....bbbbbb......",
    "ff.bbbbbbbbbb....",
    "ffbdddddddddbeb..",
    "ffbbbbbbbbbbbbbb.",
    "ff.bbbbbbbbbb....",
    "f....bbbbbb......",
  ],
};

export const JELLY_FRAMES = [
  [
    "..bbbbb..",
    ".bbbbbbb.",
    ".bebbbeb.",
    ".bbbbbbb.",
    "..f.f.f..",
    "..f.f.f..",
    ".f..f..f.",
  ],
  [
    "..bbbbb..",
    ".bbbbbbb.",
    ".bebbbeb.",
    ".bbbbbbb.",
    "..f.f.f..",
    ".f..f..f.",
    "..f.f.f..",
  ],
];

export const CRAB_FRAMES = [
  [
    ".e.......e.",
    ".b.......b.",
    "..bbbbbbb..",
    ".bbbbbbbbb.",
    "f.bbbbbbb.f",
    ".f.b.b.b.f.",
    "..d..d..d..",
  ],
  [
    ".e.......e.",
    ".b.......b.",
    "..bbbbbbb..",
    ".bbbbbbbbb.",
    "f.bbbbbbb.f",
    ".f.b.b.b.f.",
    ".d..d..d...",
  ],
];

export const SHARK_SPRITE = [
  "..........dd..............",
  ".........dddd.............",
  "d.......bbbbbbbb..........",
  "dd....bbbbbbbbbbbbb.......",
  "ddd.bbbbbbbbbbbbbbbbbeb...",
  "ddbbbbbbbbbbbbbbbbbbbbbbww",
  "ddd.bbbbbbbbbbbbbbbbbbb...",
  "dd....bbbbbbbbbbbbbb......",
  "d.......bbbdd.............",
  "...........dd.............",
];

export const SHARK_PAL = { b: "#5a7186", d: "#3c4f61", f: "#3c4f61" };

export const MANTIS_SPRITE = [
  "...........e..e.",
  "...........b..b.",
  "....bbbbbbbbbb..",
  "..bbbdbbdbbdbbb.",
  ".bbbbdbbdbbdbbc.",
  "dbbbbbbbbbbbbff.",
  "db...b.b.b..fff.",
  ".d..........ff..",
  "............f...",
];

export const MANTIS_PAL = { b: "#2fbf68", d: "#1e9e86", f: "#ff5c5c" };

export const SPECIES_DEF = [
  { key: "tetra",  w: 22 },
  { key: "guppy",  w: 22 },
  { key: "angel",  w: 16 },
  { key: "puffer", w: 14, name: "puffy",    pal: { b: "#c8b45a", d: "#8a7a2e", f: "#e0d07a" } },
  { key: "jelly",  w: 10, name: "jellyfin", pal: { b: "#b18cff", d: "#7a5cc4", f: "#8fb8ff" } },
  { key: "crab",   w: 8,  name: "ferris",   pal: { b: "#ff7043", d: "#c24a20", f: "#ff9a70" } },
  { key: "whale",  w: 5,  name: "moby",     pal: { b: "#5f8fd4", d: "#3a5e96", f: "#7fb0ea" } },
  { key: "golden", w: 4,  name: "sudo",     pal: { b: "#ffd54a", d: "#c79a1e", f: "#ffe89a" } },
  { key: "starfish", w: 5, name: "star",    pal: { b: "#ff8a5c", d: "#c25a30", f: "#ff8a5c" } },
  { key: "seahorse", w: 6, name: "pony" },
  { key: "clown",  w: 12, name: "nemo",     pal: { b: "#ff8c42", d: "#f5f5f5", f: "#e0561e" } },
  { key: "sword",  w: 5,  name: "marlin",   pal: { b: "#4f7fae", d: "#2e5480", f: "#7fa8d0" } },
  { key: "beluga", w: 2,  name: "bora",     pal: { b: "#e9f2f8", d: "#b9c9d8", f: "#d3e2ec" } },
  { key: "goldfish", w: 14, name: "bboong", pal: { b: "#ff9a3c", d: "#d96a10", f: "#ffb85e" } },
  { key: "zebra",  w: 10, name: "dash",     pal: { b: "#e8eef4", d: "#4a6ab8", f: "#c8d4e4" } },
  { key: "molly",  w: 8,  name: "mole",     pal: { b: "#454c5a", d: "#22262e", f: "#5c6577" } },
  { key: "betta",  w: 5,  name: "ruby",     pal: { b: "#c23a6e", d: "#7a1f4a", f: "#7a5cc4" } },
  { key: "discus", w: 4,  name: "disco",    pal: { b: "#e0853c", d: "#8a4a1e", f: "#c96a2e" } },
  { key: "bluetang", w: 4, name: "tang",    pal: { b: "#2e5fd4", d: "#16307a", f: "#ffd54a" } },
  { key: "arowana", w: 1.5, name: "ryong",  pal: { b: "#d4823c", d: "#8a3a1e", f: "#ffb44a" } },
  { key: "coelacanth", w: 1, name: "fossil", pal: { b: "#5a6e8c", d: "#8ea2c0", f: "#43536e" } },
  { key: "mola",   w: 1,  name: "mola",     pal: { b: "#9aa8b8", d: "#5f6e80", f: "#7a8a9c" } },
  // deep-sea dwellers: never spawn naturally (w 0), egg-only once their layer is open
  { key: "bluewhale", w: 0, name: "bloo",   pal: { b: "#4a7ab8", d: "#2e4f80", f: "#6f9cd4" } },
  { key: "hatchet", w: 0, name: "axel",     pal: { b: "#c8d8e8", d: "#8aa0b8", f: "#a8bcd0" } },
  { key: "angler",  w: 0, name: "lumen",    pal: { b: "#3a4456", d: "#262e3e", f: "#2a3242" } },
  { key: "gulper",  w: 0, name: "gulp",     pal: { b: "#2e3646", d: "#1e2430", f: "#3e4a5e" } },
  { key: "oarfish", w: 0, name: "ribbon",   pal: { b: "#dde6f0", d: "#ff5c5c", f: "#ff8a8a" } },
  { key: "giantsquid", w: 0, name: "inky",  pal: { b: "#c25a4a", d: "#8a3a2e", f: "#d98a70" } },
  { key: "cory",    w: 10, name: "dot",     pal: { b: "#c9a86a", d: "#7a5c34", f: "#e0c48a" } },
  { key: "catfish", w: 4,  name: "murk",    pal: { b: "#6e6252", d: "#463e30", f: "#8a7c66" } },
  { key: "lionfish", w: 4, name: "mane",    pal: { b: "#d4543c", d: "#f0e0d0", f: "#c23a2a" } },
  { key: "moray",   w: 3,  name: "eely",    pal: { b: "#6a8a3c", d: "#465e24", f: "#8aac5c" } },
  { key: "octopus", w: 3,  name: "octo",    pal: { b: "#c05a6a", d: "#8a3a48", f: "#d88a94" } },
  { key: "ray",     w: 1.5, name: "flap",   pal: { b: "#b8965a", d: "#7a5f34", f: "#d0b47e" } },
  { key: "turtle",  w: 1,  name: "tank",    pal: { b: "#3c8a5c", d: "#26593c", f: "#8ac89a" } },
  { key: "dolphin", w: 0.8, name: "echo",   pal: { b: "#8fa8bc", d: "#5c7488", f: "#b4c8d8" } },
  // mythic apex + seasonal visitors: egg-only (w 0)
  { key: "orca",    w: 0,  name: "willy",   pal: { b: "#1e242e", d: "#f0f4f8", f: "#2e3844" } },
  { key: "narwhal", w: 0,  name: "uni",     pal: { b: "#c8d2dc", d: "#8a98a8", f: "#aebac6" } },
  { key: "cherrysalmon", w: 0, name: "cherry", pal: { b: "#e88a9a", d: "#b85468", f: "#f4b4c0" } },
  { key: "seabream", w: 0, name: "dom",     pal: { b: "#e06a5a", d: "#a83c30", f: "#f09a8a" } },
  { key: "butterflyfish", w: 0, name: "flutter", pal: { b: "#ffd24a", d: "#2a2a30", f: "#ffe89a" } },
  { key: "mackerel", w: 0, name: "mack",    pal: { b: "#4a8ab0", d: "#2a5a7a", f: "#9ac4d8" } },
  { key: "flyingfish", w: 0, name: "glide", pal: { b: "#7aa4c8", d: "#48708e", f: "#c8dcea" } },
  { key: "manta",   w: 0,  name: "kite",    pal: { b: "#2e4258", d: "#e8f0f6", f: "#43596e" } },
  { key: "salmon",  w: 0,  name: "sam",     pal: { b: "#c88a84", d: "#8a5450", f: "#e0b0aa" } },
  { key: "gizzardshad", w: 0, name: "jeon", pal: { b: "#b8c4cc", d: "#748088", f: "#d8e0e6" } },
  { key: "cutlass", w: 0,  name: "sabre",   pal: { b: "#d8e0ea", d: "#98a4b2", f: "#eef2f8" } },
  { key: "cod",     w: 0,  name: "mook",    pal: { b: "#8a7a58", d: "#5a4e36", f: "#b0a078" } },
  { key: "icefish", w: 0,  name: "frost",   pal: { b: "#c4d8e8", d: "#8aa8c0", f: "#e0eef8" } },
  { key: "yellowtail", w: 0, name: "buri",  pal: { b: "#9ab0c0", d: "#e8c83c", f: "#ffd54a" } },
];

export const DEEP_REQ = { hatchet: 1, angler: 1, gulper: 2, oarfish: 2, giantsquid: 2, bluewhale: 1, beluga: 1 };

export const EGG_ROWS = [
  ".bbb.",
  "bhhbb",
  "bhbbb",
  "bbbbd",
  "bbbdd",
  ".bdd.",
];

export const EGG_PALS = [
  { b: "#fff3dd", h: "#fffdf4", d: "#d9b98a" }, // common (and legacy species-fixed eggs)
  { b: "#9fd0f5", h: "#d8eeff", d: "#5f8fd4" }, // premium
  { b: "#ffe17a", h: "#fff6c9", d: "#c79a1e" }, // legendary
  { b: "#c98fff", h: "#efe0ff", d: "#8a55cc" }, // mythic
];

export const COIN_ROWS = [
  "...ooo...",
  ".oohhyoo.",
  ".ohhyyyo.",
  "ohhyyyyso",
  "ohyyyyyso",
  "oyyyyysso",
  ".oyyysso.",
  ".oosssoo.",
  "...ooo...",
];

export const COIN_COLORS = { o: "#1a1208", h: "#fff2b8", y: "#ffd54a", s: "#d99b26" };
